package generator

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ActionTypeScriptGenerator generates type-safe action helpers for TypeScript.
type ActionTypeScriptGenerator struct {
	actions []string
}

// NewActionTypeScriptGenerator creates a new action TypeScript generator.
func NewActionTypeScriptGenerator() *ActionTypeScriptGenerator {
	return &ActionTypeScriptGenerator{}
}

// ScanCodebase scans the project for RegisterRemoteAction calls.
func (g *ActionTypeScriptGenerator) ScanCodebase(dir string) error {
	fset := token.NewFileSet()

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		if info.IsDir() {
			// Skip hidden directories (e.g., .kilo, .git, .github)
			if strings.HasPrefix(info.Name(), ".") && info.Name() != "." {
				return filepath.SkipDir
			}
			// Skip vendor and node_modules
			if info.Name() == "vendor" || info.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil // Skip files that fail to parse
		}

		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}

			// Look for routing.RegisterRemoteAction or RegisterRemoteAction
			if sel.Sel.Name == "RegisterRemoteAction" {
				if len(call.Args) > 0 {
					if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
						name := strings.Trim(lit.Value, "\"")
						g.actions = append(g.actions, name)
					}
				}
			}
			return true
		})

		return nil
	})

	sort.Strings(g.actions)
	// Remove duplicates
	if len(g.actions) > 1 {
		unique := make([]string, 0, len(g.actions))
		prev := ""
		for _, a := range g.actions {
			if a != prev {
				unique = append(unique, a)
				prev = a
			}
		}
		g.actions = unique
	}

	return err
}

// GenerateActionsFile generates an actions.ts file.
func (g *ActionTypeScriptGenerator) GenerateActionsFile(outputDir string) error {
	var sb strings.Builder

	sb.WriteString("// Code generated by GoSPA. DO NOT EDIT.\n")
	sb.WriteString("// Run: go generate ./...\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * All registered Remote Actions.\n")
	sb.WriteString(" */\n")
	sb.WriteString("export interface RemoteActions {\n")
	for _, action := range g.actions {
		fmt.Fprintf(&sb, "  %s: (input: any) => Promise<any>;\n", action)
	}
	sb.WriteString("}\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Type-safe way to call a remote action.\n")
	sb.WriteString(" */\n")
	sb.WriteString("export function remoteAction<T extends keyof RemoteActions>(name: T, input: any): Promise<any> {\n")
	sb.WriteString("  // @ts-ignore - Global GoSPA runtime will handle this\n")
	sb.WriteString("  return window.GoSPA.remoteAction(name, input);\n")
	sb.WriteString("}\n")

	outPath := filepath.Join(outputDir, "actions.ts")
	return os.WriteFile(outPath, []byte(sb.String()), 0600)
}
