package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateRoutesFile_EmitsTypedRouteActions(t *testing.T) {
	t.Parallel()

	routes := []RouteInfo{
		{
			URLPath:    "/",
			HasLoader:  true,
			HasActions: true,
			Actions:    []string{"default", "publish"},
		},
		{
			URLPath:   "/about",
			HasLoader: true,
		},
	}

	gen := NewRouteTypeScriptGenerator(routes, "github.com/example/app")
	outDir := t.TempDir()
	if err := gen.GenerateRoutesFile(outDir); err != nil {
		t.Fatalf("GenerateRoutesFile failed: %v", err)
	}

	//nolint:gosec // outDir is created by t.TempDir() and routes.ts is generated by this test.
	content, err := os.ReadFile(filepath.Join(outDir, "routes.ts"))
	if err != nil {
		t.Fatalf("read generated routes.ts: %v", err)
	}
	text := string(content)

	if !strings.Contains(text, `export type RouteActionName<T extends RoutePath> =`) {
		t.Fatalf("expected RouteActionName type in output")
	}
	if !strings.Contains(text, `T extends "/" ? "default" | "publish" :`) {
		t.Fatalf("expected action-name union for root route, got:\n%s", text)
	}
	if !strings.Contains(text, `export async function callRouteAction<`) {
		t.Fatalf("expected callRouteAction helper in output")
	}
	if !strings.Contains(text, `actionURL.searchParams.set('_action', String(action));`) {
		t.Fatalf("expected _action query param assignment in helper")
	}
}
