// Code generated by GoSPA. DO NOT EDIT.
// TypeScript Definitions for Go Structs

export interface componentContextKey {
}

export interface BuildSummary {
	BunPath: string;
	ClientRuntimeBuilt: boolean;
	ClientRuntimePath: string;
	GoBinaryPath: string;
	StaticFilesCopied: number;
	CompressedFiles: number;
}

export interface CardHeaderProps {
	Class: string;
}

export interface BuildAllConfig {
	Compress: boolean;
	Manifest: boolean;
	Parallel: number;
	Targets: string[];
	OutputDir: string;
}

export interface IslandConfig {
	Name: string;
	HydrationMode: IslandHydrationMode;
	Priority: IslandPriority;
	ClientOnly: boolean;
	ServerOnly: boolean;
	LazyThreshold: number;
	DeferDelay: number;
}

export interface Metadata {
	description: string;
	author: string;
	source: string;
	resolvedRef: string;
	name: string;
	version: string;
}

export interface RemoteRegistry {
}

export interface ConnectionRateLimiter {
}

export interface PropSchema {
}

export interface SkeletonTableProps {
	Rows: number;
	Columns: number;
	ShowHeader: boolean;
	Class: string;
	ID: string;
}

export interface Info {
	Author: string;
	State: State;
	Name: string;
	Version: string;
	Description: string;
}

export interface StreamWriter {
}

export interface SearchIndexEntry {
	description: string;
	url: string;
	content: string;
	section: string;
	sections: Section[];
	title: string;
}

export interface SnippetNode {
	Name: string;
	Args: string;
	Children: Node[];
}

export interface sessionEntry {
	clientId: string;
	expiresAt: string;
}

export interface FormatConfig {
	jpeg: boolean;
	png: boolean;
	webP: boolean;
	avif: boolean;
}

export interface MetaParams {
	Title: string;
	Description: string;
	Keywords: string[];
	Canonical: string;
	OGImage: string;
}

export interface ActionTypeScriptGenerator {
}

export interface Claims {
	role: string;
	user_id: string;
	email: string;
}

export interface ssgEntry {
}

export interface StateMap {
	OnChange: any;
}

export interface NestedLayout {
}

export interface IslandRegistry {
}

export interface IslandData {
	id: string;
	props: Record<string, any>;
	state: Record<string, any>;
}

export interface PropDefinition {
	DefaultValue: any;
	Required: boolean;
	Validator: any;
	Name: string;
	Type: any;
}

export interface LayoutChain {
	Layouts: Layout | null[];
	Page: any;
	Error: any;
}

export interface Store {
}

export interface IslandOptions {
	Priority: any;
	ClientOnly: boolean;
	ServerOnly: boolean;
	LazyThreshold: number;
	DeferDelay: number;
	Class: string;
	Tag: string;
	HydrationMode: any;
}

export interface SwitchCase {
}

export interface DevConfig {
	WatchPaths: string[];
	Debounce: any;
	AllowInsecureWS: boolean;
	HMRManager: HMRManager | null;
	Enabled: boolean;
	ComponentsDir: string;
	IgnorePaths: string[];
	OnReload: any;
	StateKey: string;
	RoutesDir: string;
}

export interface CompileOptions {
	Type: ComponentType;
	IslandID: string;
	PkgName: string;
	Hydrate: boolean;
	ServerOnly: boolean;
	SafeMode: boolean;
	Name: string;
	HydrateMode: string;
	RuntimeTier: RuntimeTier;
}

export interface StreamingCompressionWriter {
}

export interface HMRConfig {
	enabled: boolean;
	watchPaths: string[];
	ignorePaths: string[];
	debounceTime: any;
	allowInsecureWS: boolean;
}

export interface HMRFileChangeEvent {
	path: string;
	eventType: string;
	timestamp: string;
}

export interface Dimension {
	height: number;
	name: string;
	width: number;
}

export interface StateMapComparison {
	added: Record<string, any>;
	removed: Record<string, any>;
	changed: Record<string, any>;
}

export interface DevWatcher {
	Events: any;
	Errors: any;
}

export interface Island {
	ID: string;
	Config: IslandConfig;
	Props: Record<string, any>;
	State: Record<string, any>;
	Children: string;
}

export interface CriticalCSSConfig {
	criticalContent: string[];
	enabled: boolean;
	criticalOutput: string;
	nonCriticalOutput: string;
	dimensions: Dimension[];
	inlineMaxSize: number;
}

export interface PluginConfig {
	forms: boolean;
	aspectRatio: boolean;
	autoprefixer: boolean;
	cssnano: boolean;
	postcssNested: boolean;
	typography: boolean;
}

export interface IslandRenderer {
}

export interface compressionHandler {
}

export interface Rune {
}

export interface positionIndex {
}

export interface startupCheckOptions {
	RuntimeScript: string;
	WebSocketPath: string;
	EnableWebSocket: boolean;
	ExpectCSPNonce: boolean;
}

export interface TemplateParser {
}

export interface ReactiveDetector {
}

export interface Organization {
	name: string;
	url: string;
	logo: string;
}

export interface BaseNode {
	EndColumn: number;
	StartLine: number;
	StartColumn: number;
	EndLine: number;
}

export interface CommentNode {
	Content: string;
}

export interface NavigationIdleCallbackBatchUpdatesConfig {
	enabled: boolean | null;
	fallbackToMicrotask: boolean | null;
}

export interface NavigationProgressBarConfig {
	enabled: boolean | null;
	color: string | null;
	height: string | null;
	delay: number | null;
}

export interface CompressionConfig {
	MinSize: number;
	CompressibleTypes: string[];
	SkipPaths: string[];
	MaxBufferedSize: number;
	EnableBrotli: boolean;
	EnableGzip: boolean;
	BrotliLevel: number;
	GzipLevel: number;
}

export interface SSEConfig {
	HeartbeatInterval: any;
	OnConnect: any;
	OnDisconnect: any;
	PubSub: any;
	AuthorizeSubscribe: any;
	EventBufferSize: number;
}

export interface WSClient {
	Send: any;
	State: any | null;
	ID: string;
	SessionID: string;
	Conn: any | null;
}

export interface RouteTypeScriptGenerator {
}

export interface ModalHeaderProps {
	Class: string;
}

export interface HMRUpdatePayload {
	moduleId: string;
	path: string;
	updateType: string;
	content: string;
	statePreserve: boolean;
}

export interface AuthPlugin {
}

export interface Slot {
	Content: any;
	Name: string;
}

export interface StreamRenderer {
}

export interface jsonCheck {
	required: boolean;
	passed: boolean;
	error: string;
	name: string;
	detail: string;
}

export interface doctorCheck {
	Name: string;
	Detail: string;
	Required: boolean;
	Err: error;
}

export interface IfNode {
	Condition: string;
	Then: Node[];
	ElseIfs: ElseIfNode[];
	Else: Node[];
}

export interface PriorityIsland {
	name: string;
	mode: IslandHydrationMode;
	metadata: Record<string, any>;
	priority: PriorityLevel;
	dependencies: string[];
	state: any;
	script: string;
	position: number;
	id: string;
}

export interface SSEHelper {
}

export interface routeSegment {
}

export interface DoctorConfig {
	Fix: boolean;
	JSONOutput: boolean;
	Quiet: boolean;
	CheckUpdates: boolean;
	Strict: boolean;
	RoutesDir: string;
}

export interface TypeScriptField {
	Name: string;
	Type: string;
	Optional: boolean;
}

export interface TextNode {
	Content: string;
}

export interface BadgeProps {
	ID: string;
	Text: string;
	Variant: BadgeVariant;
	Size: BadgeSize;
	Class: string;
}

export interface Registry {
}

export interface ServeConfig {
	Port: number;
	Host: string;
	Cert: string;
	Brotli: boolean;
	Dir: string;
	HTTPS: boolean;
	Key: string;
	Open: boolean;
	Gzip: boolean;
	Cache: boolean;
	Headers: Record<string, string>;
}

export interface ActionRedirect {
	to: string;
	status: number;
}

export interface SkeletonProps {
	Variant: SkeletonVariant;
	Class: string;
	Animated: boolean;
	ID: string;
	Width: string;
	Height: string;
}

export interface DevTools {
}

export interface FieldSchema {
	type: string;
	required: boolean;
	min: any;
	max: any;
	pattern: string;
	message: string;
	default: any;
}

export interface OGParams {
	Image: string;
	URL: string;
	Type: string;
	Title: string;
	Description: string;
}

export interface SessionStore {
}

export interface BackupCode {
	Code: string;
	Used: boolean;
	UsedAt: string | null;
}

export interface Derived {
}

export interface Binding {
	Transform: string;
	Type: BindingType;
	Key: string;
	Attr: string;
}

export interface pprShellKey {
}

export interface reactiveHint {
}

export interface PaginatedMessages {
	messages: Message[];
	total: number;
	page: number;
	pageSize: number;
	totalPages: number;
}

export interface registryEntry {
}

export interface FuncParam {
	Name: string;
	Type: string;
}

export interface LayoutData {
	Data: Record<string, any>;
	Children: any;
}

export interface BaseComponent {
}

export interface ComponentTree {
}

export interface PreloadConfig {
	NavigationScript: string;
	WebSocketScript: string;
	CoreScript: string;
	MicroScript: string;
	CSSLinks: string[];
	Enabled: boolean;
	BuildManifest: Record<string, string>;
	RuntimeScript: string;
}

export interface buildResult {
}

export interface MessageInput {
	name: string;
	content: string;
}

export interface App {
	Config: Config;
	Router: any | null;
	Fiber: any | null;
	Hub: any | null;
	StateMap: any | null;
}

export interface GospaCompiler {
}

export interface NavigationOptions {
	speculativePrefetching: NavigationSpeculativePrefetchingConfig | null;
	urlParsingCache: NavigationURLParsingCacheConfig | null;
	idleCallbackBatchUpdates: NavigationIdleCallbackBatchUpdatesConfig | null;
	lazyRuntimeInitialization: NavigationLazyRuntimeInitializationConfig | null;
	serviceWorkerNavigationCaching: NavigationServiceWorkerCachingConfig | null;
	viewTransitions: NavigationViewTransitionsConfig | null;
	progressBar: NavigationProgressBarConfig | null;
}

export interface StateLogEntry {
	timestamp: string;
	key: string;
	oldValue: any;
	newValue: any;
	source: string;
}

export interface OTPConfig {
	Secret: string;
	Digits: number;
	Period: number;
	Issuer: string;
	Account: string;
}

export interface ComponentContext {
	Component: Component | null;
	Parent: ComponentContext | null;
	Context: any;
}

export interface CircularDependencyError {
	ID: string;
}

export interface WSHub {
	Clients: Record<string, WSClient | null>;
	ClientsBySession: Record<string, Record<string, WSClient | null>>;
	ClientsByTopic: Record<string, Record<string, WSClient | null>>;
	Register: any;
	Unregister: any;
	Broadcast: any;
}

export interface WebSocketConfig {
	Hub: WSHub | null;
	OnDisconnect: any;
	OnMessage: any;
	GenerateID: any;
	StateDiffing: boolean;
	Serializer: any;
	Deserializer: any;
	WSMaxMessageSize: number;
	OnConnect: any;
	CompressState: boolean;
	SerializationFormat: string;
}

export interface ImagePlugin {
}

export interface PruningConfig {
	reportFile: string;
	rootDir: string;
	outputDir: string;
	excludePatterns: string[];
	includePatterns: string[];
	keepUnused: boolean;
	aggressive: boolean;
}

export interface Layout {
	Name: string;
	Render: LayoutFunc;
	Loader: LayoutLoader;
}

export interface BuildSection {
	CGO: boolean;
	LDFlags: string;
	Compress: boolean;
	SourceMap: boolean;
	Env: string;
	AssetsDir: string;
	Tags: string;
	Targets: Target[];
	Output: string;
	Minify: boolean;
}

export interface testRuntimePlugin {
}

export interface ReactiveBoundary {
	priority: IslandPriority;
	metadata: Record<string, any>;
	lineNumber: number;
	dependencies: string[];
	stateVars: string[];
	props: string[];
	name: string;
	type: BoundaryType;
	isIsland: boolean;
	hydrationMode: IslandHydrationMode;
}

export interface routeKey {
}

export interface routeCacheStats {
	invalidations: number;
	hits: number;
	misses: number;
	staleServed: number;
	revalidations: number;
}

export interface subscriber {
}

export interface StackFrame {
	source: string;
	file: string;
	line: number;
	function: string;
}

export interface Route {
	Path: string;
	File: string;
	Type: RouteType;
	Params: string[];
	Layout: Route | null;
	Middleware: string[];
	IsDynamic: boolean;
	IsCatchAll: boolean;
	Priority: number;
	Children: Route | null[];
}

export interface importSpec {
}

export interface RouteInfo {
	ComponentFn: string;
	DynamicParam: string;
	RouteParams: string[];
	IsLayout: boolean;
	HasActions: boolean;
	Actions: string[];
	FilePath: string;
	IsError: boolean;
	IsDynamic: boolean;
	ImportPath: string;
	HasLoader: boolean;
	RuntimeTier: string;
	URLPath: string;
	Params: FuncParam[];
	PackageName: string;
	ActionFuncs: Record<string, string>;
	HasPageOptions: boolean;
}

export interface CleanConfig {
	DryRun: boolean;
	NodeModules: boolean;
	Generated: boolean;
	Dist: boolean;
	All: boolean;
	Cache: boolean;
}

export interface ProjectConfig {
	Module: string;
	OutputDir: string;
	WithGit: boolean;
	WithDocker: boolean;
	Template: string;
	NonInteractive: boolean;
	PackageManager: string;
	Name: string;
}

export interface doctorRunResult {
}

export interface FailError {
	Status: number;
	Data: any;
}

export interface searchEntry {
	url: string;
}

export interface ExpressionNode {
	Content: string;
}

export interface ErrorHandlerConfig {
	OnError: any;
	RecoverState: boolean;
	DevMode: boolean;
	StateKey: string;
	CustomErrorPages: Record<string, any>;
}

export interface ManualRoute {
	Component: any;
	Middleware: Middleware[];
	Priority: number;
	Handler: Handler;
	Params: string[];
	IsDynamic: boolean;
	Meta: Record<string, any>;
	Path: string;
	Method: string;
}

export interface StateTree {
	size: number;
	children: Record<string, StateTree | null>;
	used: boolean;
	path: string;
	name: string;
	type: string;
}

export interface GoSPAConfig {
	Generate: GenerateSection;
	Serve: ServeSection;
	Plugins: PluginConfig[];
	BuildAll: BuildAllSection;
	Version: string;
	Project: ProjectSection;
	Dev: DevSection;
	Build: BuildSection;
}

export interface LayoutProps {
	Params: Record<string, string>;
	Path: string;
	Data: Record<string, any>;
	Children: any;
	Slots: Record<string, any>;
}

export interface ColorPrinter {
}

export interface HydrationPlan {
	idle: PriorityIsland | null[];
	visible: PriorityIsland | null[];
	interaction: PriorityIsland | null[];
	lazy: PriorityIsland | null[];
	preload: string[];
	immediate: PriorityIsland | null[];
}

export interface BindableProps {
}

export interface testPlugin {
}

export interface StateMessage {
	timestamp: number;
	type: string;
	componentId: string;
	key: string;
	value: any;
	state: any;
	error: string;
}

export interface ModalFooterProps {
	Class: string;
}

export interface NavigationURLParsingCacheConfig {
	enabled: boolean | null;
	maxSize: number | null;
	ttl: number | null;
}

export interface RequestInfo {
	headers: Record<string, string>;
	query: Record<string, string>;
	method: string;
	url: string;
}

export interface Plugin {
}

export interface LayoutNode {
	Parent: LayoutNode | null;
	Route: Route | null;
	Children: LayoutNode | null[];
}

export interface ManualRouter {
}

export interface DocPage {
	title: string;
	description: string;
	url: string;
	content: string;
	sections: Section[];
}

export interface ServeSection {
	Port: number;
	Gzip: boolean;
	Brotli: boolean;
	Cache: boolean;
	Headers: Record<string, string>;
}

export interface HMRManager {
}

export interface PubSub {
}

export interface GenerateSection {
	Output: string;
	Type: string;
	Strict: boolean;
}

export interface FileEvent {
	File: string;
	Op: FileOp;
	ModTime: string;
}

export interface DetectionResult {
	islandCount: number;
	componentName: string;
	filePath: string;
	boundaries: ReactiveBoundary[];
	stateCount: number;
	derivedCount: number;
	effectCount: number;
}

export interface memoryEntry {
}

export interface HeadManager {
}

export interface RemoteActionInfo {
	Name: string;
	InputType: string;
	OutputType: string;
	FunctionType: string;
}

export interface BundleEntry {
	name: string;
	input: string;
	output: string;
	content: string[];
	criticalCSS: CriticalCSSConfig | null;
}

export interface PathBuilder {
}

export interface RouteOptions {
	Strategy: RenderStrategy;
	RevalidateAfter: any;
	DynamicSlots: string[];
	DeferredSlots: string[];
	RuntimeTier: string;
	RateLimit: RateLimitOptions | null;
}

export interface FileWatcher {
}

export interface ErrorOverlayConfig {
	ShowStack: boolean;
	ShowRequest: boolean;
	ShowCode: boolean;
	Theme: string;
	Editor: string;
	EditorPort: number;
	Enabled: boolean;
}

export interface rateBucket {
	tokens: number;
	lastRefill: string;
}

export interface otpRateEntry {
}

export interface pprEntry {
}

export interface QueryParams {
}

export interface layoutContextKey {
}

export interface ComponentNode {
	Name: string;
	Attributes: Attribute[];
	Children: Node[];
}

export interface CompressedContent {
	Gzip: byte[];
	Original: byte[];
	Brotli: byte[];
}

export interface SizeConfig {
	quality: number;
	name: string;
	width: number;
	height: number;
}

export interface LayoutResolver {
}

export interface Section {
	title: string;
	text: string;
	id: string;
}

export interface Target {
	Platform: string;
	Arch: string;
}

export interface State {
	Name: string;
	InitialValue: string;
	Type: string;
}

export interface StaticCompressionMiddleware {
}

export interface SSEClient {
	ConnectedAt: string;
	Metadata: Record<string, any>;
	Topics: Record<string, boolean>;
	ID: string;
	Channel: any;
}

export interface Flag {
	Shorthand: string;
	Description: string;
	Default: any;
	Name: string;
}

export interface headerHandler {
}

export interface broadcastJob {
}

export interface PruneConfig {
	RootDir: string;
	OutputDir: string;
	ReportFile: string;
	Exclude: string[];
	Include: string[];
	KeepUnused: boolean;
	Aggressive: boolean;
	DryRun: boolean;
	Verbose: boolean;
	JSONOutput: boolean;
}

export interface CardBodyProps {
	Class: string;
}

export interface ParamExtractor {
}

export interface MemoryStorage {
}

export interface OAuthProvider {
	Name: string;
	ClientID: string;
	ClientSecret: string;
	AuthURL: string;
	TokenURL: string;
	UserURL: string;
	Scopes: string[];
}

export interface StreamChunk {
	type: string;
	id: string;
	content: string;
	data: Record<string, any>;
}

export interface Attribute {
	Name: string;
	Value: string;
	IsExpression: boolean;
}

export interface ArticleData {
	author: string;
	datePublished: string;
	image: string;
	headline: string;
}

export interface RouteGroup {
	Prefix: string;
	Middleware: Middleware[];
	Routes: ManualRoute | null[];
	Groups: RouteGroup | null[];
	Parent: RouteGroup | null;
	Meta: Record<string, any>;
}

export interface RemoteContext {
	RequestID: string;
	SessionID: string;
	Headers: Record<string, string>;
	IP: string;
	UserAgent: string;
}

export interface StatePruner {
}

export interface MemoryPubSub {
}

export interface InputProps {
	Class: string;
	Value: string;
	Error: boolean;
	Max: string;
	Step: string;
	MaxLength: number;
	MinLength: number;
	Size: InputSize;
	Required: boolean;
	AutoFocus: boolean;
	ErrorMessage: string;
	HelperText: string;
	Attributes: any;
	Pattern: string;
	Type: InputType;
	Placeholder: string;
	ReadOnly: boolean;
	Min: string;
	AutoComplete: string;
	Label: string;
	ID: string;
	Name: string;
	DefaultValue: string;
	Disabled: boolean;
}

export interface HMRMessage {
	error: string;
	timestamp: number;
	type: string;
	path: string;
	moduleId: string;
	event: string;
	reloadReason: string;
	state: any;
}

export interface StreamRendererConfig {
	FlushInterval: any;
	BufferSize: number;
	IslandRegistry: any | null;
}

export interface ProjectSection {
	Name: string;
	Module: string;
}

export interface TypeScriptType {
	Name: string;
	Fields: TypeScriptField[];
}

export interface SFC {
	FrontMatter: Record<string, string>;
	Script: Block;
	ScriptModule: Block;
	ScriptTS: Block;
	Template: Block;
	Style: Block;
}

export interface PruningReport {
	totalStateVars: number;
	usedStateVars: number;
	prunedStateVars: number;
	estimatedSavings: number;
	stateUsage: Record<string, StateUsage>;
	prunedFiles: string[];
	errors: string[];
}

export interface StateDiff {
	componentId: string;
	key: string;
	oldValue: any;
	newValue: any;
	timestamp: number;
}

export interface targetSpec {
}

export interface ElseIfNode {
	Condition: string;
	Then: Node[];
}

export interface CardProps {
	ID: string;
	Class: string;
	Padding: boolean;
	Shadow: boolean;
	Hover: boolean;
	Attributes: any;
	Title: string;
	Subtitle: string;
	Border: boolean;
	Rounded: boolean;
}

export interface DiagnosticError {
	Column: number;
	Message: string;
	Suggestion: string;
	Snippet: string;
	Line: number;
}

export interface AlertProps {
	Message: string;
	Variant: AlertVariant;
	Dismissible: boolean;
	Class: string;
	ID: string;
	Title: string;
}

export interface StateUsage {
	type: string;
	references: string[];
	isExported: boolean;
	isUsed: boolean;
	canPrune: boolean;
	name: string;
	file: string;
	line: number;
}

export interface cacheHandler {
}

export interface RateLimitOptions {
	Window: any;
	Message: string;
	MaxRequests: number;
}

export interface stateNotification {
}

export interface ComponentState {
	State: any | null;
	Bindings: Record<string, Binding>;
	ID: string;
}

export interface ActionValidationError {
	fieldErrors: Record<string, string>;
	formError: string;
}

export interface HydrationStrategy {
	mode: IslandHydrationMode;
	priority: IslandPriority;
	reason: string;
	dependencies: string[];
	criticalPath: boolean;
}

export interface Config {
	generateTypes: boolean;
	generateServer: boolean;
	generateClient: boolean;
	strictMode: boolean;
	customValidators: string[];
	schemasDir: string;
	outputDir: string;
}

export interface ErrorInfo {
	stack: StackFrame[];
	file: string;
	line: number;
	column: number;
	codeSnippet: string;
	request: RequestInfo | null;
	message: string;
	type: string;
	timestamp: number;
	cause: ErrorInfo | null;
}

export interface TailwindPlugin {
}

export interface Router {
}

export interface Component {
	ID: string;
	Name: string;
	State: ComponentState | null;
	Props: Record<string, any>;
	Children: any;
	Slots: Record<string, any>;
}

export interface WSMessage {
	type: string;
	componentId: string;
	action: string;
	data: Record<string, any>;
	payload: any;
	sessionToken: string;
	clientId: string;
}

export interface BuildAllSection {
	Manifest: boolean;
	Parallel: number;
	Targets: string[];
	OutputDir: string;
	Compress: boolean;
}

export interface GenerateConfig {
	Strict: boolean;
	RouteFiles: string[];
	ComponentType: string;
	NoTypes: boolean;
	RoutesOnly: boolean;
	NoTempl: boolean;
	InputDir: string;
	OutputDir: string;
	StateFiles: string[];
	DevMode: boolean;
	Watch: boolean;
	NoActions: boolean;
}

export interface Dependency {
	Type: DependencyType;
	Name: string;
	Version: string;
}

export interface SPAConfig {
	Stylesheets: string[];
	Head: any;
	Body: any;
	RuntimeSrc: string;
	Meta: MetaTag[];
	RootID: string;
	AutoInit: boolean;
	Lang: string;
	Title: string;
}

export interface StreamOptions {
	CriticalIslands: string[];
	DeferBelowFold: boolean;
	MaxBufferSize: number;
	EnableProgressiveHydration: boolean;
}

export interface RequestResult {
	StatusCode: number;
	Duration: any;
	Error: error;
}

export interface NavigationSpeculativePrefetchingConfig {
	enabled: boolean | null;
	ttl: number | null;
	hoverDelay: number | null;
	viewportMargin: number | null;
}

export interface WSStateUpdate {
	key: string;
	value: any;
}

export interface BenchmarkStats {
	Errors: string[];
	Concurrency: number;
	StatusCodes: Record<string, number>;
	P95Latency: any;
	P99Latency: any;
	BytesReceived: number;
	TotalRequests: number;
	SuccessfulRequests: number;
	FailedRequests: number;
	TotalDuration: any;
	MaxLatency: any;
	MedianLatency: any;
	MinLatency: any;
	AvgLatency: any;
	RequestsPerSecond: number;
}

export interface DevSection {
	Open: boolean;
	HMRPort: number;
	Debounce: any;
	RoutesDir: string;
	WatchPaths: string[];
	Proxy: string;
	Timeout: any;
	Port: number;
	Host: string;
}

export interface slotCacheStat {
	renders: number;
	errors: number;
}

export interface PriorityQueue {
}

export interface ModalBodyProps {
	Class: string;
}

export interface batchState {
}

export interface StateValidator {
}

export interface BindableProp {
}

export interface NavigationServiceWorkerCachingConfig {
	enabled: boolean | null;
	cacheName: string;
	path: string;
}

export interface SSEBroker {
}

export interface dependency {
}

export interface MetaTag {
	Name: string;
	Content: string;
}

export interface MetaConfig {
	title: string;
	noIndex: boolean;
	noFollow: boolean;
	modified: string;
	changeFreq: string;
	description: string;
	image: string;
	keywords: string[];
	canonical: string;
	priority: number;
	path: string;
}

export interface batchContextKey {
}

export interface Effect {
}

export interface subEntry {
}

export interface SuspenseOptions {
	ErrorFallback: any;
	Retry: boolean;
}

export interface cacheStatsSnapshot {
	generatedAt: string;
	routes: Record<string, routeCacheStats>;
	slots: Record<string, slotCacheStat>;
}

export interface EachNode {
	Iteratee: string;
	As: string;
	Children: Node[];
}

export interface RawStructuredData {
	@type: string;
	@context: string;
	Properties: Record<string, any>;
}

export interface LayoutTree {
	Root: LayoutNode | null;
}

export interface LayoutContext {
	Chain: LayoutChain | null;
	Params: Record<string, string>;
	Path: string;
	Data: Record<string, any>;
}

export interface Category {
	Name: string;
	Order: number;
	Prefix: string;
}

export interface compressionJob {
}

export interface RouteMatch {
	URL: any | null;
	Route: Route | null;
	PathParams: Params;
	QueryParams: QueryParams | null;
}

export interface nonceKey {
}

export interface BuildConfig {
	Tags: string;
	NoStatic: boolean;
	OutputDir: string;
	Arch: string;
	Minify: boolean;
	Compress: boolean;
	AssetsDir: string;
	Watch: boolean;
	Platform: string;
	LDFlags: string;
	NoManifest: boolean;
	NoCompress: boolean;
	SourceMap: boolean;
	CGO: boolean;
	StaticAssets: boolean;
	Env: string;
	NoSourceMap: boolean;
}

export interface ButtonProps {
	Variant: ButtonVariant;
	Href: string;
	Target: string;
	Class: string;
	Attributes: any;
	Onclick: string;
	Size: ButtonSize;
	Disabled: boolean;
	Loading: boolean;
	FullWidth: boolean;
	Type: string;
	ID: string;
}

export interface Message {
	timestamp: string;
	id: number;
	name: string;
	content: string;
}

export interface ClientStateStore {
}

export interface staticLoadContext {
}

export interface ActionResponse {
	data: any;
	code: string;
	error: string;
	redirect: ActionRedirect | null;
	validation: ActionValidationError | null;
	revalidate: string[];
	revalidateTags: string[];
	revalidateKeys: string[];
}

export interface ComponentAnalysis {
	filePath: string;
	boundaries: ReactiveBoundary[];
	isReactive: boolean;
	shouldIsland: boolean;
	hydrationStrategy: HydrationStrategy;
	componentName: string;
}

export interface SkeletonTextProps {
	ID: string;
	Lines: number;
	LineHeight: string;
	LastLineWidth: string;
	Class: string;
}

export interface ExternalPluginLoader {
}

export interface Prop {
	Name: string;
	Type: string;
}

export interface PriorityConfig {
	maxConcurrent: number;
	idleTimeout: number;
	intersectionThreshold: number;
	intersectionRootMargin: string;
	enablePreload: boolean;
}

export interface CardFooterProps {
	Class: string;
}

export interface HMRFileWatcher {
}

export interface HeadElement {
	Tag: string;
	Attrs: Record<string, string>;
	Content: string;
	Key: string;
	Priority: number;
}

export interface NavigationLazyRuntimeInitializationConfig {
	enabled: boolean | null;
	deferBindings: boolean | null;
}

export interface fiberLoadContext {
}

export interface RegistryEntry {
	version: string;
	installed: boolean;
	name: string;
	description: string;
	url: string;
}

export interface DeferredIsland {
	Loader: any;
	Name: string;
	Placeholder: any;
}

export interface Lifecycle {
}

export interface AppError {
	stack: string;
	StatusCode: number;
	Recover: boolean;
	code: ErrorCode;
	message: string;
	details: Record<string, any>;
}

export interface Command {
	Name: string;
	Alias: string;
	Description: string;
	Action: any;
	Flags: Flag[];
}

export interface TwitterParams {
	Card: string;
	Title: string;
	Description: string;
	Image: string;
	Site: string;
}

export interface SSEEvent {
	retry: number;
	id: string;
	event: string;
	data: any;
}

export interface Spinner {
}

export interface NavigationViewTransitionsConfig {
	enabled: boolean | null;
	fallbackToClassic: boolean | null;
}

export interface PostCSSPlugin {
}

export interface ElementNode {
	SelfClosing: boolean;
	TagName: string;
	Attributes: Attribute[];
	Children: Node[];
}

export interface MessageStore {
}

export interface Schema {
	name: string;
	fields: Record<string, FieldSchema>;
}

export interface FileInfo {
	Path: string;
	Size: number;
	Category: string;
	Order: number;
}

export interface RedirectError {
	Status: number;
	Location: string;
}

export interface ModalProps {
	CloseOnEscape: boolean;
	ShowCloseButton: boolean;
	Class: string;
	ID: string;
	Title: string;
	Size: ModalSize;
	Open: boolean;
	CloseOnOverlay: boolean;
}

export interface ErrorOverlay {
}

export interface User {
	id: string;
	email: string;
	role: string;
}

export interface EventHandler {
	Debounce: number;
	Throttle: number;
	Event: string;
	Handler: string;
	Modifiers: string[];
}

export interface VerifyConfig {
	Strict: boolean;
	RoutesDir: string;
	JSONOutput: boolean;
	Quiet: boolean;
}

export interface Block {
	ByteOffset: number;
	Line: number;
	Column: number;
	Type: string;
	Lang: string;
	Context: string;
	Content: string;
}

export interface stringLiteralRange {
}

export interface SkeletonCardProps {
	ShowTitle: boolean;
	ShowDescription: boolean;
	DescriptionLines: number;
	Class: string;
	ID: string;
	ShowImage: boolean;
	ImageHeight: string;
	ShowAvatar: boolean;
}

export interface QRCode {
	Size: number;
	Foreground: any;
	Background: any;
	Content: string;
	Level: Level;
}

export interface StateSnapshot {
	timestamp: number;
	componentId: string;
	state: Record<string, any>;
}

