// Code generated by gospa route generator. DO NOT EDIT.
// Run: go generate ./...

package routes

import (
	"strconv"

	"github.com/a-h/templ"
	"github.com/aydenstechdungeon/gospa/routing"
	"github.com/aydenstechdungeon/gospa/website/routes/docs"
	docsapi "github.com/aydenstechdungeon/gospa/website/routes/docs/api"
	docsapiclient "github.com/aydenstechdungeon/gospa/website/routes/docs/api/client"
	docsapicore "github.com/aydenstechdungeon/gospa/website/routes/docs/api/core"
	docsapifiber "github.com/aydenstechdungeon/gospa/website/routes/docs/api/fiber"
	docsapirouting "github.com/aydenstechdungeon/gospa/website/routes/docs/api/routing"
	docsapistate "github.com/aydenstechdungeon/gospa/website/routes/docs/api/state"
	docscli "github.com/aydenstechdungeon/gospa/website/routes/docs/cli"
	docsclientruntimedombindings "github.com/aydenstechdungeon/gospa/website/routes/docs/client-runtime/dom-bindings"
	docsclientruntimenavigationevents "github.com/aydenstechdungeon/gospa/website/routes/docs/client-runtime/navigation-events"
	docsclientruntimeoverview "github.com/aydenstechdungeon/gospa/website/routes/docs/client-runtime/overview"
	docsclientruntimetransitions "github.com/aydenstechdungeon/gospa/website/routes/docs/client-runtime/transitions"
	docsclientruntimewebsocket "github.com/aydenstechdungeon/gospa/website/routes/docs/client-runtime/websocket"
	docscomponents "github.com/aydenstechdungeon/gospa/website/routes/docs/components"
	docsconfiguration "github.com/aydenstechdungeon/gospa/website/routes/docs/configuration"
	docsconfigurationbasic "github.com/aydenstechdungeon/gospa/website/routes/docs/configuration/basic"
	docsconfigurationscaling "github.com/aydenstechdungeon/gospa/website/routes/docs/configuration/scaling"
	docsconfigurationwebsocket "github.com/aydenstechdungeon/gospa/website/routes/docs/configuration/websocket"
	docsdevtools "github.com/aydenstechdungeon/gospa/website/routes/docs/devtools"
	docserrors "github.com/aydenstechdungeon/gospa/website/routes/docs/errors"
	docsfaq "github.com/aydenstechdungeon/gospa/website/routes/docs/faq"
	docsgetstartedinstallation "github.com/aydenstechdungeon/gospa/website/routes/docs/getstarted/installation"
	docsgetstartedquickstart "github.com/aydenstechdungeon/gospa/website/routes/docs/getstarted/quickstart"
	docsgetstartedstructure "github.com/aydenstechdungeon/gospa/website/routes/docs/getstarted/structure"
	docsgospasfc "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc"
	docsgospasfcadvanced "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/advanced"
	docsgospasfcexamples "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/examples"
	docsgospasfcgettingstarted "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/getting-started"
	docsgospasfcreactivity "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/reactivity"
	docsgospasfcstyles "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/styles"
	docsgospasfctemplates "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/templates"
	docsgospasfctypescript "github.com/aydenstechdungeon/gospa/website/routes/docs/gospasfc/typescript"
	docshmr "github.com/aydenstechdungeon/gospa/website/routes/docs/hmr"
	docsislands "github.com/aydenstechdungeon/gospa/website/routes/docs/islands"
	docsparams "github.com/aydenstechdungeon/gospa/website/routes/docs/params"
	docsplugins "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins"
	docspluginsauth "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/auth"
	docspluginsimage "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/image"
	docspluginspostcss "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/postcss"
	docspluginsqrcode "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/qrcode"
	docspluginsseo "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/seo"
	docspluginstailwind "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/tailwind"
	docspluginsvalidation "github.com/aydenstechdungeon/gospa/website/routes/docs/plugins/validation"
	docsreactiveprimitives "github.com/aydenstechdungeon/gospa/website/routes/docs/reactive-primitives"
	docsreactiveprimitivesadvanced "github.com/aydenstechdungeon/gospa/website/routes/docs/reactive-primitives/advanced"
	docsreactiveprimitivesgo "github.com/aydenstechdungeon/gospa/website/routes/docs/reactive-primitives/go"
	docsreactiveprimitivesjs "github.com/aydenstechdungeon/gospa/website/routes/docs/reactive-primitives/js"
	docsremoteactions "github.com/aydenstechdungeon/gospa/website/routes/docs/remote-actions"
	docsrendering "github.com/aydenstechdungeon/gospa/website/routes/docs/rendering"
	docsrouting "github.com/aydenstechdungeon/gospa/website/routes/docs/routing"
	docsroutingapi "github.com/aydenstechdungeon/gospa/website/routes/docs/routing/api"
	docsroutingdynamic "github.com/aydenstechdungeon/gospa/website/routes/docs/routing/dynamic"
	docsroutinglayouts "github.com/aydenstechdungeon/gospa/website/routes/docs/routing/layouts"
	docsroutingnavigation "github.com/aydenstechdungeon/gospa/website/routes/docs/routing/navigation"
	docsruntime "github.com/aydenstechdungeon/gospa/website/routes/docs/runtime"
	docssse "github.com/aydenstechdungeon/gospa/website/routes/docs/sse"
	docsstatemanagement "github.com/aydenstechdungeon/gospa/website/routes/docs/state-management"
	docsstatemanagementclient "github.com/aydenstechdungeon/gospa/website/routes/docs/state-management/client"
	docsstatemanagementpatterns "github.com/aydenstechdungeon/gospa/website/routes/docs/state-management/patterns"
	docsstatemanagementserver "github.com/aydenstechdungeon/gospa/website/routes/docs/state-management/server"
	docsstatemanagementsync "github.com/aydenstechdungeon/gospa/website/routes/docs/state-management/sync"
	docstroubleshooting "github.com/aydenstechdungeon/gospa/website/routes/docs/troubleshooting"
	docswebsocket "github.com/aydenstechdungeon/gospa/website/routes/docs/websocket"
)

func mergeRouteOptions(base routing.RouteOptions, override routing.RouteOptions) routing.RouteOptions {
	if override.Strategy != "" {
		base.Strategy = override.Strategy
	}
	if override.RevalidateAfter > 0 {
		base.RevalidateAfter = override.RevalidateAfter
	}
	if len(override.DynamicSlots) > 0 {
		base.DynamicSlots = override.DynamicSlots
	}
	if len(override.DeferredSlots) > 0 {
		base.DeferredSlots = override.DeferredSlots
	}
	if override.RuntimeTier != "" {
		base.RuntimeTier = override.RuntimeTier
	}
	if override.RateLimit != nil {
		base.RateLimit = override.RateLimit
	}
	return base
}

func init() {
	// Register pages
	routing.RegisterPageWithOptions("/", func(props map[string]interface{}) templ.Component {
		return Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs", func(props map[string]interface{}) templ.Component {
		return docs.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api", func(props map[string]interface{}) templ.Component {
		return docsapi.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api/client", func(props map[string]interface{}) templ.Component {
		return docsapiclient.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api/core", func(props map[string]interface{}) templ.Component {
		return docsapicore.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api/fiber", func(props map[string]interface{}) templ.Component {
		return docsapifiber.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api/routing", func(props map[string]interface{}) templ.Component {
		return docsapirouting.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/api/state", func(props map[string]interface{}) templ.Component {
		return docsapistate.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/cli", func(props map[string]interface{}) templ.Component {
		return docscli.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/client-runtime/dom-bindings", func(props map[string]interface{}) templ.Component {
		return docsclientruntimedombindings.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/client-runtime/navigation-events", func(props map[string]interface{}) templ.Component {
		return docsclientruntimenavigationevents.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/client-runtime/overview", func(props map[string]interface{}) templ.Component {
		return docsclientruntimeoverview.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/client-runtime/transitions", func(props map[string]interface{}) templ.Component {
		return docsclientruntimetransitions.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/client-runtime/websocket", func(props map[string]interface{}) templ.Component {
		return docsclientruntimewebsocket.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/components", func(props map[string]interface{}) templ.Component {
		return docscomponents.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/configuration", func(props map[string]interface{}) templ.Component {
		return docsconfiguration.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/configuration/basic", func(props map[string]interface{}) templ.Component {
		return docsconfigurationbasic.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/configuration/scaling", func(props map[string]interface{}) templ.Component {
		return docsconfigurationscaling.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/configuration/websocket", func(props map[string]interface{}) templ.Component {
		return docsconfigurationwebsocket.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/devtools", func(props map[string]interface{}) templ.Component {
		return docsdevtools.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/errors", func(props map[string]interface{}) templ.Component {
		return docserrors.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/faq", func(props map[string]interface{}) templ.Component {
		return docsfaq.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/getstarted/installation", func(props map[string]interface{}) templ.Component {
		return docsgetstartedinstallation.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/getstarted/quickstart", func(props map[string]interface{}) templ.Component {
		return docsgetstartedquickstart.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/getstarted/structure", func(props map[string]interface{}) templ.Component {
		return docsgetstartedstructure.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/gospasfc", func(props map[string]interface{}) templ.Component {
		return docsgospasfc.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/advanced", func(props map[string]interface{}) templ.Component {
		return docsgospasfcadvanced.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/examples", func(props map[string]interface{}) templ.Component {
		return docsgospasfcexamples.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/getting-started", func(props map[string]interface{}) templ.Component {
		return docsgospasfcgettingstarted.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/reactivity", func(props map[string]interface{}) templ.Component {
		return docsgospasfcreactivity.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/styles", func(props map[string]interface{}) templ.Component {
		return docsgospasfcstyles.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/templates", func(props map[string]interface{}) templ.Component {
		return docsgospasfctemplates.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/gospasfc/typescript", func(props map[string]interface{}) templ.Component {
		return docsgospasfctypescript.Page()
	}, routing.RouteOptions{RuntimeTier: "micro"})
	routing.RegisterPageWithOptions("/docs/hmr", func(props map[string]interface{}) templ.Component {
		return docshmr.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/islands", func(props map[string]interface{}) templ.Component {
		return docsislands.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/params", func(props map[string]interface{}) templ.Component {
		return docsparams.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins", func(props map[string]interface{}) templ.Component {
		return docsplugins.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/auth", func(props map[string]interface{}) templ.Component {
		return docspluginsauth.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/image", func(props map[string]interface{}) templ.Component {
		return docspluginsimage.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/postcss", func(props map[string]interface{}) templ.Component {
		return docspluginspostcss.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/qrcode", func(props map[string]interface{}) templ.Component {
		return docspluginsqrcode.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/seo", func(props map[string]interface{}) templ.Component {
		return docspluginsseo.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/tailwind", func(props map[string]interface{}) templ.Component {
		return docspluginstailwind.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/plugins/validation", func(props map[string]interface{}) templ.Component {
		return docspluginsvalidation.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/reactive-primitives", func(props map[string]interface{}) templ.Component {
		return docsreactiveprimitives.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/reactive-primitives/advanced", func(props map[string]interface{}) templ.Component {
		return docsreactiveprimitivesadvanced.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/reactive-primitives/go", func(props map[string]interface{}) templ.Component {
		return docsreactiveprimitivesgo.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/reactive-primitives/js", func(props map[string]interface{}) templ.Component {
		return docsreactiveprimitivesjs.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/remote-actions", func(props map[string]interface{}) templ.Component {
		return docsremoteactions.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/rendering", func(props map[string]interface{}) templ.Component {
		return docsrendering.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/routing", func(props map[string]interface{}) templ.Component {
		return docsrouting.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/routing/api", func(props map[string]interface{}) templ.Component {
		return docsroutingapi.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/routing/dynamic", func(props map[string]interface{}) templ.Component {
		return docsroutingdynamic.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/routing/layouts", func(props map[string]interface{}) templ.Component {
		return docsroutinglayouts.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/routing/navigation", func(props map[string]interface{}) templ.Component {
		return docsroutingnavigation.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/runtime", func(props map[string]interface{}) templ.Component {
		return docsruntime.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/sse", func(props map[string]interface{}) templ.Component {
		return docssse.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/state-management", func(props map[string]interface{}) templ.Component {
		return docsstatemanagement.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/state-management/client", func(props map[string]interface{}) templ.Component {
		return docsstatemanagementclient.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/state-management/patterns", func(props map[string]interface{}) templ.Component {
		return docsstatemanagementpatterns.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/state-management/server", func(props map[string]interface{}) templ.Component {
		return docsstatemanagementserver.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/state-management/sync", func(props map[string]interface{}) templ.Component {
		return docsstatemanagementsync.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/troubleshooting", func(props map[string]interface{}) templ.Component {
		return docstroubleshooting.Page()
	}, routing.RouteOptions{RuntimeTier: ""})
	routing.RegisterPageWithOptions("/docs/websocket", func(props map[string]interface{}) templ.Component {
		return docswebsocket.Page()
	}, routing.RouteOptions{RuntimeTier: ""})

	// Register layouts
	routing.RegisterRootLayout(func(children templ.Component, props map[string]interface{}) templ.Component {
		return RootLayout(func() string {
		if v, ok := props["title"].(string); ok {
			return v
		}
		return ""
	}(), children, func() string {
		if v, ok := props["runtimePath"].(string); ok {
			return v
		}
		return ""
	}(), func() string {
		if v, ok := props["path"].(string); ok {
			return v
		}
		return ""
	}(), func() string {
		if v, ok := props["wsUrl"].(string); ok {
			return v
		}
		return ""
	}(), func() bool {
		if v, ok := props["debug"].(bool); ok {
			return v
		}
		if v, ok := props["debug"].(string); ok {
			parsed, err := strconv.ParseBool(v)
			if err == nil {
				return parsed
			}
		}
		return false
	}(), func() string {
		if v, ok := props["hydrationMode"].(string); ok {
			return v
		}
		return ""
	}(), func() int {
		if v, ok := props["hydrationTimeout"].(int); ok {
			return v
		}
		if v, ok := props["hydrationTimeout"].(string); ok {
			parsed, err := strconv.ParseInt(v, 10, 64)
			if err == nil {
				return int(parsed)
			}
		}
		return 0
	}(), func() string {
		if v, ok := props["serializationFormat"].(string); ok {
			return v
		}
		return ""
	}())
	}, "")
	routing.RegisterLayoutWithOptions("/docs", func(children templ.Component, props map[string]interface{}) templ.Component {
		return docs.DocsLayout(children, func() string {
		if v, ok := props["path"].(string); ok {
			return v
		}
		return ""
	}())
	}, "")
}
