// Code generated by gospa route generator. DO NOT EDIT.
// Run: go generate ./...

package routes

import (
	docsrouting "website/routes/docs/routing"
	docsstatemanagement "website/routes/docs/state-management"
	"github.com/aydenstechdungeon/gospa/routing"
	docscomponents "website/routes/docs/components"
	docsparams "website/routes/docs/params"
	docsruntime "website/routes/docs/runtime"
	docsclientruntime "website/routes/docs/client-runtime"
	docsgetstarted "website/routes/docs/getstarted"
	"website/routes/docs"
	docsreactiveprimitives "website/routes/docs/reactive-primitives"
	docsconfiguration "website/routes/docs/configuration"
	docsremoteactions "website/routes/docs/remote-actions"
	docssecurity "website/routes/docs/security"
	docswebsocket "website/routes/docs/websocket"
	"github.com/a-h/templ"
	docsapi "website/routes/docs/api"
	docscli "website/routes/docs/cli"
	docsdevtools "website/routes/docs/devtools"
	docserrors "website/routes/docs/errors"
)

func init() {
	// Register pages
	routing.RegisterPage("/docs/api", func(props map[string]interface{}) templ.Component {
		return docsapi.Page()
	})
	routing.RegisterPage("/docs/cli", func(props map[string]interface{}) templ.Component {
		return docscli.Page()
	})
	routing.RegisterPage("/docs/client-runtime", func(props map[string]interface{}) templ.Component {
		return docsclientruntime.Page()
	})
	routing.RegisterPage("/docs/components", func(props map[string]interface{}) templ.Component {
		return docscomponents.Page()
	})
	routing.RegisterPage("/docs/configuration", func(props map[string]interface{}) templ.Component {
		return docsconfiguration.Page()
	})
	routing.RegisterPage("/docs/devtools", func(props map[string]interface{}) templ.Component {
		return docsdevtools.Page()
	})
	routing.RegisterPage("/docs/errors", func(props map[string]interface{}) templ.Component {
		return docserrors.Page()
	})
	routing.RegisterPage("/docs/getstarted", func(props map[string]interface{}) templ.Component {
		return docsgetstarted.Page()
	})
	routing.RegisterPage("/docs", func(props map[string]interface{}) templ.Component {
		return docs.Page()
	})
	routing.RegisterPage("/docs/params", func(props map[string]interface{}) templ.Component {
		return docsparams.Page()
	})
	routing.RegisterPage("/docs/reactive-primitives", func(props map[string]interface{}) templ.Component {
		return docsreactiveprimitives.Page()
	})
	routing.RegisterPage("/docs/remote-actions", func(props map[string]interface{}) templ.Component {
		return docsremoteactions.Page()
	})
	routing.RegisterPage("/docs/routing", func(props map[string]interface{}) templ.Component {
		return docsrouting.Page()
	})
	routing.RegisterPage("/docs/runtime", func(props map[string]interface{}) templ.Component {
		return docsruntime.Page()
	})
	routing.RegisterPage("/docs/security", func(props map[string]interface{}) templ.Component {
		return docssecurity.Page()
	})
	routing.RegisterPage("/docs/state-management", func(props map[string]interface{}) templ.Component {
		return docsstatemanagement.Page()
	})
	routing.RegisterPage("/docs/websocket", func(props map[string]interface{}) templ.Component {
		return docswebsocket.Page()
	})
	routing.RegisterPage("/", func(props map[string]interface{}) templ.Component {
		return Page()
	})

	// Register layouts
	routing.RegisterLayout("/docs", func(children templ.Component, props map[string]interface{}) templ.Component {
		return docs.DocsLayout(children, func() string {
		if v, ok := props["path"].(string); ok {
			return v
		}
		return ""
	}())
	})
	routing.RegisterRootLayout(func(children templ.Component, props map[string]interface{}) templ.Component {
		return RootLayout(func() string {
		if v, ok := props["title"].(string); ok {
			return v
		}
		return ""
	}(), children, func() string {
		if v, ok := props["runtimePath"].(string); ok {
			return v
		}
		return ""
	}(), func() string {
		if v, ok := props["path"].(string); ok {
			return v
		}
		return ""
	}(), func() string {
		if v, ok := props["wsUrl"].(string); ok {
			return v
		}
		return ""
	}(), func() bool {
		if v, ok := props["debug"].(bool); ok {
			return v
		}
		return false
	}(), func() string {
		if v, ok := props["hydrationMode"].(string); ok {
			return v
		}
		return ""
	}(), func() int {
		if v, ok := props["hydrationTimeout"].(int); ok {
			return v
		}
		return 0
	}())
	})
}
