// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package configuration

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/aydenstechdungeon/gospa/website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Configuration</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">Complete reference for all gospa.Config options. Configure your GoSPA application for development, production, and scale.</p><p class=\"text-sm text-[var(--text-muted)] mt-4\">Full Markdown (tables, security notes, every field):  <a href=\"https://github.com/aydenstechdungeon/gospa/blob/main/docs/configuration.md\" class=\"text-[var(--accent-primary)] hover:underline\" rel=\"noopener noreferrer\">docs/configuration.md</a> on GitHub.</p></header><section class=\"space-y-4\"><h2 class=\"text-2xl font-bold\">Quick Start</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`app := gospa.New(gospa.Config{
    RoutesDir: "./routes",
    DevMode:   true,
    AppName:   "My App",
})`, "go", " main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Configuration Topics</h2><div class=\"grid md:grid-cols-2 gap-4\"><a href=\"/docs/configuration/basic\" class=\"p-6 rounded-2xl bg-[var(--bg-secondary)] border border-[var(--border)] hover:border-[var(--accent-primary)]/50 transition-all group\"><h3 class=\"font-bold mb-2 group-hover:text-[var(--accent-primary)]\">Basic and State</h3><p class=\"text-sm text-[var(--text-secondary)]\">RoutesDir, DevMode, AppName, DefaultState, and serializers.</p></a> <a href=\"/docs/configuration/websocket\" class=\"p-6 rounded-2xl bg-[var(--bg-secondary)] border border-[var(--border)] hover:border-[var(--accent-primary)]/50 transition-all group\"><h3 class=\"font-bold mb-2 group-hover:text-[var(--accent-primary)]\">WebSocket and Performance</h3><p class=\"text-sm text-[var(--text-secondary)]\">WebSocket settings, compression, diffing, and caching.</p></a> <a href=\"/docs/configuration/scaling\" class=\"p-6 rounded-2xl bg-[var(--bg-secondary)] border border-[var(--border)] hover:border-[var(--accent-primary)]/50 transition-all group\"><h3 class=\"font-bold mb-2 group-hover:text-[var(--accent-primary)]\">Scaling and Security</h3><p class=\"text-sm text-[var(--text-secondary)]\">Prefork, Redis storage, CORS, CSRF, and hydration modes.</p></a></div></section><section class=\"space-y-4\"><h2 class=\"text-2xl font-bold\">Environment-Specific Examples</h2><h3 class=\"text-xl font-semibold\">Development</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`app := gospa.New(gospa.Config{
    DevMode:     true,
    AppName:     "My App (Dev)",
    RoutesDir:   "./routes",
    SimpleRuntime: false,
})`, "go", " main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h3 class=\"text-xl font-semibold mt-6\">Production</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`app := gospa.New(gospa.Config{
    DevMode:         false,
    AppName:         "My App",
    RoutesDir:       "./routes",
    CompressState:   true,
    StateDiffing:    true,
    CacheTemplates:  true,
    EnableCSRF:      true,
    AllowedOrigins:  []string{"https://myapp.com"},
    WSHeartbeat:     30 * time.Second,
})`, "go", " main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</section><section class=\"space-y-4\"><h2 class=\"text-2xl font-bold\">Complete Example</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`package main

import (
    "time"
    "github.com/aydenstechdungeon/gospa"
)

func main() {
    app := gospa.New(gospa.Config{
        RoutesDir: "./routes",
        AppName:   "My Application",
        DevMode:   true,
        
        DefaultState: map[string]interface{}{
            "theme": " dark",
            "user":  nil,
        },
        
        EnableWebSocket:    true,
        WebSocketPath:      "/_gospa/ws",
        WSReconnectDelay:   100 * time.Millisecond,
        WSMaxReconnect:     10,
        WSHeartbeat:        30 * time.Second,
        
        CompressState:  true,
        StateDiffing:   true,
        CacheTemplates: true,
        
        HydrationMode:    "visible",
        HydrationTimeout: 3000,
        
        AllowedOrigins: []string{"https://myapp.com"},
        EnableCSRF:     true,
    })
    
    if err := app.Run(":3000"); err != nil {
        panic(err)
    }
}`, "go", " main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
