// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package cli

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/aydenstechdungeon/gospa/website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">CLI Reference</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">The current GoSPA CLI centers on six supported workflows: scaffold, inspect, develop, build, generate, and clean.</p></header><section class=\"grid gap-6 lg:grid-cols-[1.3fr_0.7fr] items-start\"><div class=\"rounded-[2rem] border border-[var(--border)] bg-[var(--bg-secondary)] p-6 md:p-8 shadow-[0_20px_60px_rgba(0,0,0,0.12)]\"><div class=\"flex items-center gap-3 mb-5\"><div class=\"px-3 py-1 rounded-full text-xs font-bold uppercase tracking-[0.28em] bg-[var(--accent-primary)]/10 text-[var(--accent-primary)]\">Recommended Flow</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa create myapp
cd myapp
go mod tidy
gospa doctor
gospa dev`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"space-y-4\"><div class=\"rounded-2xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5\"><h2 class=\"font-bold mb-2\">What `doctor` gives you</h2><p class=\"text-sm text-[var(--text-secondary)] leading-relaxed\">Before you start the server, validate Go/Bun availability, project layout, and runtime entrypoints from the same CLI users already installed.</p></div><div class=\"rounded-2xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5\"><h2 class=\"font-bold mb-2\">What `build` now reports</h2><p class=\"text-sm text-[var(--text-secondary)] leading-relaxed\">Production builds now surface the Bun executable, runtime artifact path, Go binary path and size, plus copied/compressed asset counts.</p></div></div></section><section class=\"space-y-8\"><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa create</h2><p class=\"text-[var(--text-secondary)] mb-4\">Create a new GoSPA project scaffold.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa create myapp`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa doctor</h2><p class=\"text-[var(--text-secondary)] mb-4\">Check local tooling and project layout before you start development or cut a release.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa doctor
gospa doctor --routes-dir ./routes`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<ul class=\"list-disc pl-6 mt-4 space-y-2 text-[var(--text-secondary)]\"><li>Confirms Go is available.</li><li>Checks for Bun and Bun package manifests.</li><li>Validates optional app layout like `main.go`, routes, and client runtime entrypoints.</li></ul></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa dev</h2><p class=\"text-[var(--text-secondary)] mb-4\">Start the local development workflow with file watching and server restarts.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa dev
gospa dev --port 8080 --host 0.0.0.0
gospa dev --routes-dir ./routes`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa build</h2><p class=\"text-[var(--text-secondary)] mb-4\">Create a production build with Go plus Bun-based client runtime steps where applicable.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa build
gospa build -o ./dist --platform linux --arch amd64
gospa build --minify=false --compress=false`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"mt-4 rounded-2xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5\"><h3 class=\"font-bold mb-3\">Current supported flags</h3><ul class=\"space-y-2 text-sm text-[var(--text-secondary)]\"><li><code class=\"mono text-[var(--accent-primary)]\">-o</code> — output directory</li><li><code class=\"mono text-[var(--accent-primary)]\">--platform</code> — target GOOS</li><li><code class=\"mono text-[var(--accent-primary)]\">--arch</code> — target GOARCH</li><li><code class=\"mono text-[var(--accent-primary)]\">--minify</code> — enable or disable Bun minification</li><li><code class=\"mono text-[var(--accent-primary)]\">--compress</code> — enable or disable gzip precompression</li></ul></div></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa generate</h2><p class=\"text-[var(--text-secondary)] mb-4\">Generate Go routes, TypeScript types, action definitions, and route metadata. This creates <code>routes.ts</code>, <code>types.ts</code>, and <code>actions.ts</code> to enable a full type-safe bridge.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa generate
gospa generate -o ./generated --input-dir .
gospa generate --type page`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"mt-4 rounded-2xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5\"><h3 class=\"font-bold mb-3\">Generate flags</h3><ul class=\"space-y-2 text-sm text-[var(--text-secondary)]\"><li><code class=\"mono text-[var(--accent-primary)]\">--input-dir</code> — directory to scan for routes/state</li><li><code class=\"mono text-[var(--accent-primary)]\">-o</code> — output directory</li><li><code class=\"mono text-[var(--accent-primary)]\">--type</code> — default `.gospa` type (<code>island</code>, <code>page</code>, <code>layout</code>, <code>static</code>, <code>server</code>)</li></ul></div></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa clean</h2><p class=\"text-[var(--text-secondary)] mb-4\">Remove generated and build artifacts such as `dist`, `node_modules`, and templ-generated files.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa clean`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">gospa version</h2><p class=\"text-[var(--text-secondary)] mb-4\">Print the installed GoSPA version.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa version`, "bash", "terminal").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
