// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package reactiveprimitives

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"overview\" class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Reactive Primitives</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">The heart of GoSPA's reactivity consists of three core primitives: <code class=\"text-[var(--accent-primary)]\">Rune</code>, <code class=\"text-[var(--accent-primary)]\">Derived</code>, and <code class=\"text-[var(--accent-primary)]\">Effect</code>.</p></header><section class=\"space-y-6\"><div class=\"flex items-center gap-4\"><div class=\"w-12 h-12 rounded-2xl bg-[var(--accent-primary)]/10 flex items-center justify-center text-[var(--accent-primary)]\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path><polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"></polyline><line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line></svg></div><h2 id=\"runes\" class=\"text-2xl font-bold\">Rune</h2></div><p class=\"text-[var(--text-secondary)]\">A <code class=\"text-[var(--text-primary)]\">Rune</code> is the fundamental unit of state. It holds a value and notifies subscribers when that value changes.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Create a new rune with an initial value
count := gospa.NewRune(0)

// Update the value
count.Set(count.Get() + 1)

// Subscribe to changes (usually handled automatically by Templ)
count.Subscribe(func(v int) {
    fmt.Println("Count changed to:", v)
})`, "go", "main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section><section class=\"space-y-6\"><div class=\"flex items-center gap-4\"><div class=\"w-12 h-12 rounded-2xl bg-[var(--accent-secondary)]/10 flex items-center justify-center text-[var(--accent-secondary)]\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m18 16 4-4-4-4\"></path><path d=\"m6 8-4 4 4 4\"></path><path d=\"m14.5 4-5 16\"></path></svg></div><h2 id=\"derived\" class=\"text-2xl font-bold\">Derived</h2></div><p class=\"text-[var(--text-secondary)]\"><code class=\"text-[var(--text-primary)]\">Derived</code> runes are computed from other runes. They stay in sync automatically and only re-calculate when their dependencies change.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`count := gospa.NewRune(2)
doubled := gospa.Derived(count, func(v int) int {
    return v * 2
})

fmt.Println(doubled.Get()) // 4
count.Set(5)
fmt.Println(doubled.Get()) // 10`, "go", "main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><section class=\"space-y-6\"><div class=\"flex items-center gap-4\"><div class=\"w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center text-amber-500\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 2 3 14h9l-1 8 10-12h-9l1-8z\"></path></svg></div><h2 id=\"effects\" class=\"text-2xl font-bold\">Effect</h2></div><p class=\"text-[var(--text-secondary)]\"><code class=\"text-[var(--text-primary)]\">Effect</code> allows you to perform side effects (like logging, API calls, or manual DOM updates) in response to state changes.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`gospa.Effect(count, func(v int) {
    log.Printf("The count is now %d", v)
})`, "go", "main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</section><div class=\"bg-gradient-to-r from-[var(--bg-secondary)] to-[var(--bg-tertiary)] p-8 rounded-3xl border border-[var(--border)] shadow-inner\"><h3 class=\"text-lg font-bold mb-4\">Why call them \"Runes\"?</h3><p class=\"text-sm text-[var(--text-secondary)] leading-relaxed\">Inspired by Svelte 5's terminology, Runes in GoSPA represent magical symbols that imbue your data with reactive properties. They are the building blocks of an interactive UI that responds naturally to user input and server events.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
