// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package sse

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Server-Sent Events</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">Real-time, one-way push notifications from server to client. Ideal for status updates, notifications, and real-time state synchronization without the overhead of WebSockets.</p></header><section class=\"space-y-8\"><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Server-Side (Go)</h2><p class=\"text-[var(--text-secondary)] mb-4\">The SSE implementation is provided by the fiber package via the SSEBroker.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`import (
    "github.com/aydenstechdungeon/gospa/fiber"
    "time"
)

func main() {
    // 1. Create a broker
    broker := fiber.NewSSEBroker(&fiber.SSEConfig{
        EventBufferSize:   100,
        HeartbeatInterval: 30 * time.Second,
        OnConnect: func(client *fiber.SSEClient) {
            fmt.Printf("Client connected: %s\n", client.ID)
        },
    })

    app := fiber.New()

    // 2. Setup SSE routes
    fiber.SetupSSE(app, broker, "/_sse", nil)
}`, "go", "main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Broker API</h2><div class=\"overflow-x-auto\"><table class=\"w-full text-sm text-left text-[var(--text-secondary)]\"><thead class=\"text-xs uppercase bg-[var(--surface)] text-[var(--text-primary)]\"><tr><th class=\"px-4 py-2\">Method</th><th class=\"px-4 py-2\">Description</th></tr></thead> <tbody><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">NewSSEBroker(config)</td><td class=\"px-4 py-2\">Creates a new broker instance.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">Connect(clientID, metadata)</td><td class=\"px-4 py-2\">Manually registers a client.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">Disconnect(clientID)</td><td class=\"px-4 py-2\">Removes a client.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">Subscribe(clientID, topics...)</td><td class=\"px-4 py-2\">Adds a client to specific topics.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">Send(clientID, event)</td><td class=\"px-4 py-2\">Sends an event to a specific client.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">Broadcast(event)</td><td class=\"px-4 py-2\">Sends an event to all connected clients.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">BroadcastToTopic(topic, event)</td><td class=\"px-4 py-2\">Sends an event to clients in a topic.</td></tr></tbody></table></div></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">SSEHelper</h2><p class=\"text-[var(--text-secondary)] mb-4\">A high-level helper for common notification patterns:</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`helper := fiber.NewSSEHelper(broker)

// Send a basic notification
helper.Notify(clientID, map[string]string{"message": "Hello!"})

// Broadcast to everyone
helper.NotifyAll("System maintenance in 5 minutes")

// Send state update
helper.Update(clientID, "count", 42)

// Send an alert
helper.Alert(clientID, "warning", "Low disk space")

// Report progress
helper.Progress(clientID, 75, "Uploading...")`, "go", "handlers.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Client-Side (TypeScript)</h2><p class=\"text-[var(--text-secondary)] mb-4\">The client runtime provides an SSEClient to consume events with automatic reconnection and heartbeat monitoring.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`import { connectSSE } from '@gospa/runtime';

const sse = connectSSE('notifications', {
  url: '/_sse/connect',
  autoReconnect: true,
  debug: true
});`, "typescript", "app.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Event Handling</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Listen for generic messages
sse.onMessage((ev) => {
  console.log('Received:', ev.data);
});

// Listen for custom event types
sse.on('notification', (ev) => {
  showToast(ev.data.message);
});

// Listen for state updates
sse.on('update', (ev) => {
  const { key, value } = ev.data;
  console.log(`+"`"+`Update ${key} to ${value}`+"`"+`);
});

// Unsubscribe
const unsub = sse.on('alert', handleAlert);
unsub(); // Stop listening`, "typescript", "events.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Connection Management</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`sse.onStateChange((state) => {
  console.log('Connection status:', state);
  // 'connecting', 'connected', 'disconnected', 'error'
});

sse.disconnect();
sse.connect();`, "typescript", "connection.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">SSE Configuration</h2><div class=\"overflow-x-auto\"><table class=\"w-full text-sm text-left text-[var(--text-secondary)]\"><thead class=\"text-xs uppercase bg-[var(--surface)] text-[var(--text-primary)]\"><tr><th class=\"px-4 py-2\">Option</th><th class=\"px-4 py-2\">Default</th><th class=\"px-4 py-2\">Description</th></tr></thead> <tbody><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">url</td><td class=\"px-4 py-2\">-</td><td class=\"px-4 py-2\">The SSE endpoint URL.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">autoReconnect</td><td class=\"px-4 py-2\">true</td><td class=\"px-4 py-2\">Automatically reconnect on failure.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">maxRetries</td><td class=\"px-4 py-2\">5</td><td class=\"px-4 py-2\">Maximum reconnection attempts.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">reconnectDelay</td><td class=\"px-4 py-2\">1000</td><td class=\"px-4 py-2\">Initial delay before reconnecting (ms).</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">heartbeatInterval</td><td class=\"px-4 py-2\">30000</td><td class=\"px-4 py-2\">Expected heartbeat interval from server.</td></tr><tr class=\"border-b border-[var(--border)]\"><td class=\"px-4 py-2 font-mono\">debug</td><td class=\"px-4 py-2\">false</td><td class=\"px-4 py-2\">Enable verbose logging.</td></tr></tbody></table></div></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">SSEManager (Advanced)</h2><p class=\"text-[var(--text-secondary)] mb-4\">For multiple SSE connections, use the getSSEManager() API:</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`import { getSSEManager } from '@gospa/runtime';

const manager = getSSEManager();
manager.setDefaultConfig({ autoReconnect: true });

const main = manager.client('main', { url: '/_sse/main' });
const logs = manager.client('logs', { url: '/_sse/logs' });`, "typescript", "manager.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
