// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package devtools

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Development Tools</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">GoSPA includes powerful development tools for rapid iteration and debugging.</p></header><section class=\"space-y-8\"><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Hot Reload</h2><p class=\"text-[var(--text-secondary)] mb-4\">Automatic page refresh when files change.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`# Start development server with hot reload
gospa dev

# With options
gospa dev --port 3000 --watch ./routes,./components

# Hot reload behavior:
// - Template changes (.templ) -> Full page reload
// - Go code changes -> Server restart + page reload
// - Static files -> Instant refresh
// - Client TypeScript -> HMR (Hot Module Replacement)`, "bash", "cli/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">File Watching</h2><p class=\"text-[var(--text-secondary)] mb-4\">Configure which files trigger rebuilds.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// In gospa.json
{
    "watch": {
        "paths": [
            "./routes",
            "./components",
            "./lib"
        ],
        "exclude": [
            "./static/dist",
            "./node_modules"
        ],
        "debounce": "100ms"
    }
}`, "json", "cli/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">State Inspector</h2><p class=\"text-[var(--text-secondary)] mb-4\">Debug reactive state in development mode.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Enable state inspector in development
import { enableStateInspector } from 'gospa/runtime';

if (import.meta.env.DEV) {
    enableStateInspector({
        logChanges: true,      // Console log state changes
        showTimeline: true,    // Track state history
        highlightUpdates: true // Visual feedback on updates
    });
}

// Access inspector via window
window.__GOSPA_STATE_INSPECTOR__.getState();
window.__GOSPA_STATE_INSPECTOR__.getHistory();
window.__GOSPA_STATE_INSPECTOR__.reset();`, "typescript", "client/src/state.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Debug Logging</h2><p class=\"text-[var(--text-secondary)] mb-4\">Enhanced logging for development.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Server-side debug logging
// Set environment variable
GOSPA_DEBUG=true gospa dev

// Log levels
GOSPA_LOG_LEVEL=debug gospa dev  // debug, info, warn, error

// Client-side debug
import { setLogLevel } from 'gospa/runtime';
setLogLevel('debug');

// Debug specific modules
GOSPA_DEBUG=state:*,routing:* gospa dev`, "bash", "cli/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">WebSocket Debugging</h2><p class=\"text-[var(--text-secondary)] mb-4\">Monitor WebSocket communication.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Enable WebSocket debugging
import { enableWebSocketDebug } from 'gospa/runtime';

if (import.meta.env.DEV) {
    enableWebSocketDebug({
        logMessages: true,
        logLatency: true
    });
}

// Server-side WebSocket logging
// In development mode, all WebSocket messages are logged
// with timestamps and message types`, "typescript", "client/src/websocket.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Build Analysis</h2><p class=\"text-[var(--text-secondary)] mb-4\">Analyze bundle size and dependencies.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`# Analyze production build
gospa build --analyze

# Output includes:
# - Bundle size breakdown
# - Dependency tree
# - Unused code detection
# - Optimization suggestions

# Example output:
# Bundle Analysis
# ================
# Total size: 245 KB
# 
# Runtime:     45 KB (18%)
# State:       32 KB (13%)
# DOM:         28 KB (11%)
# WebSocket:   18 KB (7%)
# Your code:  122 KB (50%)`, "bash", "cli/build.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Performance Profiling</h2><p class=\"text-[var(--text-secondary)] mb-4\">Profile rendering and state updates.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Enable performance profiling
import { enableProfiling } from 'gospa/runtime';

if (import.meta.env.DEV) {
    enableProfiling({
        trackRenders: true,     // Track component renders
        trackUpdates: true,     // Track state updates
        trackEffects: true,     // Track effect execution
        slowThreshold: 16       // Warn if > 16ms (60fps)
    });
}

// Get profiling report
const report = window.__GOSPA_PROFILER__.getReport();
console.log(report.slowRenders);
console.log(report.frequentUpdates);`, "typescript", "client/src/runtime-core.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Error Overlay</h2><p class=\"text-[var(--text-secondary)] mb-4\">Development error display overlay with source code snippets, stack traces, and request information.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Server-side configuration
config := fiber.ErrorOverlayConfig{
    Enabled:     true,
    ShowStack:   true,     // Display stack traces
    ShowRequest: true,     // Show request details
    Theme:       "dark",   // "dark" or "light"
    Editor:      "code",   // Opens files in VS Code via vscode:// protocol
}

overlay := fiber.NewErrorOverlay(config)

// Auto-triggered for 500 errors in DevMode`, "go", "fiber/error_overlay.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">State Inspector Server Setup</h2><p class=\"text-[var(--text-secondary)] mb-4\">Monitor reactive state changes across server and client in real-time.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Mount Dev Panel
devTools := fiber.NewDevTools(fiber.DevConfig{
    Enabled:   true,
    RoutesDir: "./routes",
})

// Add state inspector middleware
app.Use(fiber.StateInspectorMiddleware(devTools, config))

// Mount the dev panel UI
app.Get("/_gospa/dev", devTools.DevPanelHandler())
app.Get("/_gospa/dev/ws", devTools.DevToolsHandler()) // WS for real-time updates`, "go", "fiber/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<h3 class=\"text-lg font-semibold mt-6 mb-3\">Features</h3><ul class=\"list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4\"><li><strong class=\"text-[var(--text-primary)]\">Live Change Log</strong> — See every Rune or StateMap update as it happens on both server and client</li><li><strong class=\"text-[var(--text-primary)]\">Diff View</strong> — Compare \"Before\" and \"After\" state values</li><li><strong class=\"text-[var(--text-primary)]\">Source Tracking</strong> — Identify whether a state change originated from server or client</li><li><strong class=\"text-[var(--text-primary)]\">Key Registry</strong> — Browse all currently tracked reactive state keys</li></ul></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Debug Middleware</h2><p class=\"text-[var(--text-secondary)] mb-4\">Lightweight middleware that logs every request with method, path, status, and processing time.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Add debug middleware
app.Use(fiber.DebugMiddleware(devTools))

// Logging format:
// [GET] /docs/api 200 1.2ms
// [POST] /api/users 201 45.3ms`, "go", "fiber/middleware.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Client-Side Debugging</h2><p class=\"text-[var(--text-secondary)] mb-4\">The runtime exposes internal state via <code class=\"bg-[var(--surface)] px-1 rounded\">window.__GOSPA__</code> when the auto-init attribute is present.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`<!-- Enable in HTML -->
<html data-gospa-auto>

// From browser console, you can inspect:
__GOSPA__.components   // All active component instances
__GOSPA__.globalState  // The root StateMap
__GOSPA__.config       // Active runtime configuration`, "html", "client/src/runtime.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<h3 class=\"text-lg font-semibold mt-6 mb-3\">Manual Error Reporting</h3><p class=\"text-[var(--text-secondary)] mb-4\">Trigger the error overlay programmatically from client code.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`import { displayError } from '@gospa/runtime';

displayError({
    message: "Custom validation failed",
    type: "ValidationError",
    file: "main.ts",
    line: 42
});`, "typescript", "client/src/error_overlay.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
