// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package devtools

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Development Tools</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">GoSPA includes powerful development tools for rapid iteration and debugging.</p></header><section class=\"space-y-8\"><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Hot Reload</h2><p class=\"text-[var(--text-secondary)] mb-4\">Automatic page refresh when files change.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`# Start development server with hot reload
gospa dev

# With options
gospa dev --port 3000 --routes ./routes --components ./components

# Hot reload behavior:
// - Template changes (.templ) -> Full page reload
// - Go code changes -> Server restart + page reload
// - Static files -> Instant refresh
// - Client TypeScript -> HMR (Hot Module Replacement)`, "bash", "cli/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Error Overlay</h2><p class=\"text-[var(--text-secondary)] mb-4\">Development error display overlay with source code snippets, stack traces, and request information. Automatically active when <code class=\"bg-[var(--surface)] px-1 rounded\">DevMode: true</code>.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Enabled automatically in DevMode — no extra setup needed:
app := gospa.New(gospa.Config{
    DevMode: true,
    // ...
})

// For custom configuration, create manually:
config := fiber.ErrorOverlayConfig{
    Enabled:     true,
    ShowStack:   true,     // Display stack traces
    ShowRequest: true,     // Show request details
    Theme:       "dark",   // "dark" or "light"
    Editor:      "code",   // Opens files in VS Code via vscode:// protocol
}
overlay := fiber.NewErrorOverlay(config)

// Render overlay HTML for any error:
html := overlay.RenderOverlay(err, nil)`, "go", "fiber/error_overlay.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">State Inspector</h2><p class=\"text-[var(--text-secondary)] mb-4\">Monitor reactive state changes across server and client in real-time via the dev panel at <code class=\"bg-[var(--surface)] px-1 rounded\">/_gospa/dev</code>.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Mount the state inspector in your app
devTools := fiber.NewDevTools(fiber.DevConfig{
    Enabled:   true,
    RoutesDir: "./routes",
})
devTools.Start()
defer devTools.Stop()

// Add state inspector middleware (before routes)
app.Use(fiber.StateInspectorMiddleware(devTools, config))

// Mount the dev panel UI
app.Get("/_gospa/dev", devTools.DevPanelHandler())
app.Get("/_gospa/dev/ws", devTools.DevToolsHandler())`, "go", "fiber/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<h3 class=\"text-lg font-semibold mt-6 mb-3\">Features</h3><ul class=\"list-disc list-inside text-[var(--text-secondary)] space-y-2 ml-4\"><li><strong class=\"text-[var(--text-primary)]\">Live Change Log</strong> — See every Rune or StateMap update as it happens on both server and client</li><li><strong class=\"text-[var(--text-primary)]\">Diff View</strong> — Compare \"Before\" and \"After\" state values</li><li><strong class=\"text-[var(--text-primary)]\">Source Tracking</strong> — Identify whether a state change originated from server or client</li><li><strong class=\"text-[var(--text-primary)]\">Key Registry</strong> — Browse all currently tracked reactive state keys</li></ul></div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Debug Middleware</h2><p class=\"text-[var(--text-secondary)] mb-4\">Lightweight middleware that logs every request with method, path, status, and processing time.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Add debug middleware
app.Use(fiber.DebugMiddleware(devTools))

// Logging format:
// [GET] /docs/api 200 1.2ms
// [POST] /api/users 201 45.3ms`, "go", "fiber/middleware.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Debug Logging</h2><p class=\"text-[var(--text-secondary)] mb-4\">Enhanced logging for development.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Server-side debug logging
// Set environment variable
GOSPA_DEBUG=true gospa dev

// Client-side debug — access live state from the browser console:
// (available when <html data-gospa-auto> is present)
__GOSPA__.globalState     // The root StateMap
__GOSPA__.components      // All active component instances
__GOSPA__.config          // Active runtime configuration`, "bash", "cli/dev.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">WebSocket Debugging</h2><p class=\"text-[var(--text-secondary)] mb-4\">Monitor WebSocket communication.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Server-side WebSocket logging
// In DevMode (gospa.Config{DevMode: true}), all connections and
// disconnections are logged with client IDs:
// Client connected: conn_a1b2c3d4
// Client disconnected: conn_a1b2c3d4

// From the browser console you can inspect frame-by-frame:
// Open DevTools → Network → WS → the GoSPA WebSocket connection`, "typescript", "fiber/websocket.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">Client-Side Debugging</h2><p class=\"text-[var(--text-secondary)] mb-4\">The runtime exposes internal state via <code class=\"bg-[var(--surface)] px-1 rounded\">window.__GOSPA__</code> when the auto-init attribute is present.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`<!-- Enable in HTML -->
<html data-gospa-auto>

// From browser console, you can inspect:
__GOSPA__.components   // All active component instances
__GOSPA__.globalState  // The root StateMap
__GOSPA__.config       // Active runtime configuration

// Call functions directly:
__GOSPA__.getState("myComponent", "count")
__GOSPA__.setState("myComponent", "count", 42)
__GOSPA__.callAction("myComponent", "increment")`, "html", "client/src/runtime.ts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div><h2 class=\"text-2xl font-bold mb-4 border-b border-[var(--border)] pb-2 italic mono\">State Analysis (CLI)</h2><p class=\"text-[var(--text-secondary)] mb-4\">Analyze reactive state usage and memory savings.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`# Analyze production build
# Analyze state usage and potential savings
gospa prune --dry-run --verbose

# Output includes:
# - Used vs Unused state variables
# - Source file locations
# - Estimated memory savings
# - Dependency tree analysis

# Example output:
# === State Pruning Summary ===
# Total state variables: 42
# Used state variables:  38
# Would prune variables:  4
# Estimated savings:     512 bytes`, "bash", "cli/build.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
