// Code generated by GoSPA. DO NOT EDIT.
// TypeScript Definitions for Go Structs

export interface MessageInput {
	content: string;
	name: string;
}

export interface Message {
	content: string;
	timestamp: string;
	id: number;
	name: string;
}

export interface PaginatedMessages {
	messages: Message[];
	total: number;
	page: number;
	pageSize: number;
	totalPages: number;
}

export interface MessageStore {
}

