// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package remoteactions

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"overview\" class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">Remote Actions</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">Type-safe server functions called directly from your Svelte-like templates.</p></header><section class=\"space-y-6\"><h2 id=\"defining-actions\" class=\"text-2xl font-bold\">Defining Actions</h2><p class=\"text-[var(--text-secondary)]\">Remote actions allow you to execute Go code on the server in response to client-side events. They are fully type-safe when used with the generated TypeScript bindings.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// Server-side definition
app.RegisterRemoteAction("sendMessage", func(c *gospa.Context, msg string) error {
    fmt.Printf("Message received: %s\n", msg)
    return nil
})`, "go", "main.go").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section><section class=\"space-y-6\"><h2 id=\"calling-actions\" class=\"text-2xl font-bold\">Calling from Templates</h2><p class=\"text-[var(--text-secondary)]\">Use the <code class=\"text-[var(--accent-primary)]\">data-on</code> attribute to bind events to remote actions.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`<button 
    data-on="click:remote:sendMessage('Hello Go!')"
    class="btn-primary"
>
    Send Message
</button>`, "templ", "page.templ").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><div id=\"optimistic-ui\" class=\"bg-blue-500/5 border border-blue-500/20 p-6 rounded-2xl\"><h4 class=\"text-blue-500 font-bold mb-2\">Power Feature: Optimistic UI</h4><p class=\"text-sm text-[var(--text-secondary)]\">GoSPA automatically handles state synchronization. When a remote action modifies server-side state, the client is updated instantly via WebSockets, giving you \"optimistic-like\" updates with zero effort.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
