// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package routing

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "website/components"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"overview\" class=\"space-y-12\"><header><h1 class=\"text-4xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]\">File-Based Routing</h1><p class=\"text-xl text-[var(--text-secondary)] leading-relaxed\">GoSPA uses a filesystem-based router inspired by SvelteKit and Next.js. Your directory structure defines your URL structure.</p></header><section class=\"space-y-6\"><h2 id=\"file-structure\" class=\"text-2xl font-bold\">Directory Structure</h2><p class=\"text-[var(--text-secondary)]\">Each directory in your <code class=\"text-[var(--text-primary)]\">routes/</code> folder represents a path. A <code class=\"text-[var(--text-primary)]\">page.templ</code> file inside that directory becomes the entry point for that route.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`routes/
├── page.templ             // -> /
├── about/
│   └── page.templ         // -> /about
├── blog/
│   ├── page.templ         // -> /blog
│   └── [slug]/
│       └── page.templ     // -> /blog/:slug
└── layout.templ           // Shared layout for all routes`, "text", "Project Structure").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section><section class=\"space-y-6\"><h2 id=\"dynamic-routes\" class=\"text-2xl font-bold\">Dynamic Routes</h2><p class=\"text-[var(--text-secondary)]\">Use brackets <code class=\"text-[var(--text-primary)]\">[param]</code> in directory names to create dynamic routes. These parameters are passed to your Templ components automatically.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// routes/blog/[slug]/page.templ
package blog

templ Page(props map[string]interface{}) {
    <h1>Post: { props["slug"].(string) }</h1>
}`, "go", "routes/blog/[slug]/page.templ").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><section class=\"space-y-6\"><h2 id=\"layouts\" class=\"text-2xl font-bold\">Nested Layouts</h2><p class=\"text-[var(--text-secondary)]\">You can define <code class=\"text-[var(--text-primary)]\">layout.templ</code> files at any level. They will wrap all pages and sub-layouts within that directory.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CodeBlock(`// routes/docs/layout.templ
package docs

templ Layout(children templ.Component) {
    <div class="docs-container">
        <nav class="sidebar">...</nav>
        <main>
            @children
        </main>
    </div>
}`, "go", "routes/docs/layout.templ").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</section><div class=\"p-6 rounded-2xl bg-[var(--accent-primary)]/5 border border-[var(--accent-primary)]/20\"><h4 class=\"font-bold text-[var(--accent-primary)] mb-2\">Pro Tip</h4><p class=\"text-sm text-[var(--text-secondary)]\">The route generator automatically handles imports and registration. Just add your files, and <code class=\"text-[var(--text-primary)]\">gospa dev</code> will take care of the rest.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
